Scriptname NHV_Q01Script extends NHV_ContractBaseScript
{Q01 "The Unanswered Sacrament" - Hrefna Stormhollow, Morthal/Hjaalmarch. First recruitment
contract after Q00; runs the Whisper/Hunt/Observation/Trial/Judgement/Homecoming schema from
concept section 5 for this one candidate. Stage numbers match dialogue/Journal.csv exactly and
must never be renumbered once released (docs/CONVENTIONS.md). See docs/plan/Q01-The-Unanswered-
Sacrament.md for the full design and open CK decisions. M1.7.}

; -- Aliases filled in the CK on THIS quest. VeyraAlias and the Core/PlayerRef properties used
; below are inherited from NHV_ContractBaseScript. The quest's PlayerRef alias itself carries no
; property here - it only needs NHV_ContractPlayerAliasScript attached directly to it in the CK. --
ReferenceAlias Property HakanAlias Auto
ReferenceAlias Property HrefnaAlias Auto
ReferenceAlias Property QuintusAlias Auto

; -- Globals (both already exist in plugin-text, reused, not re-created) --
GlobalVariable Property NHV_Status_Hrefna Auto      ; 000811:NightsHarvest.esp
GlobalVariable Property NHV_Flag_HrefnaUnproven Auto ; new, see docs/plan Record-Inventar
GlobalVariable Property NHV_Q01_TrialActive Auto     ; 004993; 1 while Veyra's trial runs: condition of the alias package NHV_Pkg_Q01_VeyraTrialHold

; -- NHV_Sys_Family's reserved alias for Hrefna (alias 2, "HrefnaSlot" - already exported with
; NHV_RecruitAliasScript and StatusGlobal wired, see plugin-text/Quests/NHV_Sys_Family) --
ReferenceAlias Property HrefnaFamilySlotAlias Auto

; -- World references (XMarkers, filled in the CK) --
ObjectReference Property CampMarker Auto      ; NHV_Mk_Q01_CampMarker, ambush poll target
ObjectReference Property KitchenMarker Auto   ; NHV_Mk_Q01_KitchenSpot, Homecoming destination
ObjectReference Property VeyraTrialMarker Auto ; NHV_Mk_Q01_VeyraAppearSpot, where Veyra steps out of the dark for the trial

; -- Scenes --
Scene Property CampAmbushScene Auto  ; NHV_Scn_Q01_01CampAmbush
Scene Property VeyraTrialScene Auto  ; NHV_Scn_Q01_02VeyraTrial
Scene Property QuintusApproachScene Auto ; NHV_Scn_Q01_03QuintusApproach, played when Hrefna and the player reach Quintus
Idle Property HrefnaKillIdle Auto ; optional paired dagger kill-move for the assassination; None = instant kill without animation

; -- Items --
Book Property OculatusFragment1 Auto   ; NHV_Item_OculatusFragment1
Book Property QuintusFieldNote Auto ; NHV_Book_QuintusFieldNote, found on his body
Weapon Property BogwifesKnife Auto     ; NHV_Weap_BogwifesKnife, Judgement "Recruit" reward
Book Property HrefnaReleaseLetter Auto ; NHV_Book_HrefnaReleaseLetter, delivered 7 days after Release

; -- Dialogue V2 (tools/build_q01_v2.py): the topics read cursor/state globals of NightsHarvest.esp; these constants
; are their plugin FormIDs and enum values, rewritten by the builder. --
; BEGIN FLOW CONSTANTS (generated by tools/build_q01_enhanced.py - do not edit)
Int Property FLOW_CURSOR_MAIN = 28673 AutoReadOnly
Int Property FLOW_ENTRY_PAPERS = 1005 AutoReadOnly
Int Property FLOW_ENTRY_TABLE = 1016 AutoReadOnly
Int Property FLOW_SCOUT_YIELD = 28959 AutoReadOnly
; END FLOW CONSTANTS

; Player must be within this many game units of CampMarker for the ambush to trigger. A plain
; GetDistance() comparison is used on purpose - no squared-distance literal math anywhere in this
; file (docs/CONVENTIONS.md warns the German-locale Papyrus compiler mishandles constant float
; multiplication such as "450.0 * 450.0").
Float Property CampAmbushRadius = 700.0 AutoReadOnly

; Player and Hrefna must both be this close to Quintus before the approach scene starts and Hrefna attacks.
Float Property KillApproachRadius = 600.0 AutoReadOnly

; Neither variable below needs to be read by a CK Condition, so neither carries "Conditional".
Bool bCampWatchStarted = False
Float fLetterDueGameTime = 0.0 ; absolute Utility.GetCurrentGameTime() the letter is due; 0 = none pending

; Stage 50 "Hrefna kills Quintus herself" path (29.09.2026). Additive variables, no CK condition needs them.
Bool bHrefnaWillKill = False   ; set when Persuade/Intimidate succeeded; cleared by "Step aside"
Bool bApproachStarted = False  ; approach scene was started (or skipped) once
Bool bHrefnaAttacked = False   ; Hrefna was sent into combat against Quintus once
Bool bHrefnaFought = False     ; her aggression/protection were changed and still need restoring
Int iApproachTicks = 0         ; ticks waited for the approach scene to report IsPlaying() when no lock is held
Int iAttackTries = 0           ; retries of HrefnaAttacksQuintus() while Hrefna/Quintus are not available
Float fHrefnaAggression = 0.0  ; her Aggression value before the fight

; ---------------------------------------------------------------------------
; Stage 20 -> 30: ambush watch
; ---------------------------------------------------------------------------

; Called once, from the Stage 20 fragment, after the player has read the farm/cellar documents.
; Polling here mirrors the accepted Q00 pattern (docs/ARCHITECTURE.md, "E24"): a position check
; avoids a trigger box and any navmesh edit in a vanilla exterior cell. Guarded against a double
; start (e.g. a dialogue branch re-running the fragment) so only one OnUpdate chain is ever alive.
Function BeginCampWatch()
    If bCampWatchStarted || GetStage() >= 40
        Return
    EndIf
    bCampWatchStarted = True
    RegisterForSingleUpdate(2.0)
EndFunction

; Overrides NHV_ContractBaseScript.OnUpdate(): runs the Stage 20 ambush-distance check first. Once a
; scene is locked, later ticks fall through to Parent.OnUpdate() (the base watchdog) instead. The
; two branches never both run in the SAME tick: AmbushDistanceCheck() already re-registers itself
; (still waiting) or triggers LockCutscene() (which re-registers on the scene's behalf) - calling
; Parent.OnUpdate() right after in that same tick would immediately re-read the just-set lock state
; with iCutsceneTicks still at 0 and IsPlaying() still False, a start-up race. Returning instead lets
; the NEXT tick take the Parent.OnUpdate() branch cleanly.
Event OnUpdate()
    If bKillPending
        bKillPending = False
        FinishAssassination()
    EndIf
    If bReedFightPending
        bReedFightPending = False
        ReedbedStartFight()
    EndIf
    If bReedbedWatch
        ReedbedWatchTick()
        If bReedbedWatch
            If bReedFightStarted
                RequestUpdate(2.5)
            Else
                RequestUpdate(5.0)
            EndIf
        EndIf
    EndIf
    If bDeathWatch
        DeathWatchTick()
        If bDeathWatch
            RequestUpdate(5.0)
        EndIf
    EndIf
    If bTableCursorPending
        bTableCursorPending = False
        NHV_Util.FlowSet(FLOW_CURSOR_MAIN, FLOW_ENTRY_TABLE) ; after the debrief chain reset the cursor to 0
        NHV_Util.Log(NHV_Cfg_Debug, "OpenMapTable: the table greeting is armed")
    EndIf
    If bDebriefWatch
        DebriefTick()
        If bDebriefWatch
            RegisterForSingleUpdate(4.0)
        EndIf
    EndIf
    If bVeyraWatch
        VeyraTick()
        If bVeyraWatch
            RegisterForSingleUpdate(3.0) ; later branches may set their own timer; this one only keeps the watch alive
        EndIf
    EndIf
    If iPendingScene != 0
        Int iSid = iPendingScene
        iPendingScene = 0
        NHV_Util.FlowScene(iSid)
        RearmWatches()
        Return
    EndIf
    If bWatchpostWatch
        If GetStage() == 25 && !IsCutsceneLocked()
            WatchpostCheck()
            Return
        EndIf
        If GetStage() != 25
            bWatchpostWatch = False
        ElseIf IsCutsceneLocked()
            RearmWatches() ; the base watchdog below runs this tick, the watch goes on afterwards
        EndIf
    EndIf
    If bHomeWatch
        If GetStage() >= 100 && !IsCutsceneLocked()
            HomeWatchCheck()
            Return
        EndIf
        If GetStage() < 100
            bHomeWatch = False ; quest reset (debug/MCM): forget the watch and fall through
            bHomeScenePlayed = False
        EndIf
    EndIf
    If GetStage() == 30 && !IsCutsceneLocked()
        AmbushDistanceCheck()
        Return
    EndIf
    If GetStage() == 50 && bHrefnaWillKill && !bHrefnaAttacked
        ; Kill watch (Hrefna will kill Quintus). While the approach scene locks the controls the base
        ; watchdog runs and this chain is kept alive; the tick after the unlock sends Hrefna in even if
        ; the scene's end fragment never ran (watchdog recovery, load).
        If IsCutsceneLocked()
            Parent.OnUpdate()
            RegisterForSingleUpdate(2.0)
        ElseIf bApproachStarted
            ; No lock held (Core lock skipped it, or the watchdog already released it). Never send Hrefna in
            ; while the scene is still playing; give a just-started scene a few ticks (IsPlaying() lags).
            iApproachTicks += 1
            If QuintusApproachScene && (QuintusApproachScene.IsPlaying() || iApproachTicks <= 3)
                RegisterForSingleUpdate(2.0)
            Else
                HrefnaAttacksQuintus()
            EndIf
        Else
            KillWatchCheck()
        EndIf
        Return
    EndIf
    Parent.OnUpdate()
EndEvent

Bool bCampAmbushDone = False

Function AmbushDistanceCheck()
    If GetStage() != 30
        bCampWatchStarted = False ; quest moved on (or was reset by MCM debug) - stop polling silently
        If GetStage() < 30
            bCampAmbushDone = False
        EndIf
        Return
    EndIf
    If bCampAmbushDone
        bCampWatchStarted = False
        Return
    EndIf
    Actor kPlayer = Game.GetPlayer()
    If !kPlayer || !CampMarker
        RegisterForSingleUpdate(2.0)
        Return
    EndIf
    If kPlayer.GetDistance(CampMarker) <= CampAmbushRadius
        StartCampAmbush()
    Else
        RegisterForSingleUpdate(2.0)
    EndIf
EndFunction

Function StartCampAmbush()
    If !HrefnaAlias
        NHV_Util.Log(NHV_Cfg_Debug, "StartCampAmbush: HrefnaAlias property not set in the CK")
        RegisterForSingleUpdate(2.0)
        Return
    EndIf
    Actor kHrefna = HrefnaAlias.GetActorRef()
    If !kHrefna || kHrefna.IsDead() || kHrefna.IsDisabled()
        NHV_Util.Log(NHV_Cfg_Debug, "StartCampAmbush: Hrefna unavailable, staying on Stage 20")
        RegisterForSingleUpdate(2.0) ; keep polling; she may become available again after a load
        Return
    EndIf
    If !CampAmbushScene
        NHV_Util.Log(NHV_Cfg_Debug, "StartCampAmbush: CampAmbushScene property not set in the CK")
        Return
    EndIf
    bCampWatchStarted = False
    bCampAmbushDone = True
    LockCutscene(CampAmbushScene)
    CampAmbushScene.Start()
EndFunction

; Called from the CampAmbushScene's end fragment.
Function EndCampAmbush()
    UnlockCutscene() ; Enhanced arc: the camp stage (30) was set by the scout's answer already
EndFunction

; ---------------------------------------------------------------------------
; Stage 50: Veyra's Trial
; ---------------------------------------------------------------------------

; Called from the Stage 40->50 dialogue fragment (Hrefna agrees to hear Veyra out).
Function StartVeyraTrial()
    ; Stage 50 (Trial) begins here, even when the appearance scene cannot run below - the Trial01/
    ; Persuade/Intimidate dialogue is gated on Stage 50 and must stay reachable (fallback path).
    Int iStage = GetStage()
    If iStage < 40 || iStage >= 60
        NHV_Util.Log(NHV_Cfg_Debug, "StartVeyraTrial: called in Stage " + iStage + ", ignored")
        Return
    EndIf
    If VeyraTrialScene && VeyraTrialScene.IsPlaying()
        Return ; double call (both Offer07 topics); the scene is already running
    EndIf
    Bool bFirstCall = (iStage < 50)
    If bFirstCall
        SetStage(50)
    Else
        Return ; Stage 50 already reached: the trial was started by an earlier call
    EndIf
    FillVeyraAlias() ; NHV_ContractBaseScript: ForceRefTo from NHV_CoreScript.GetVeyraActor()
    If !VeyraAlias || !VeyraAlias.GetActorRef()
        ; Optional alias unfilled (E16-style soft dependency broke, or a patch removed Veyra) -
        ; fall back to a plain dialogue-driven Stage 50 without the appearance scene. The CK
        ; wires a fallback topic for this case (docs/ck/M1.6-Q01-CK-Anleitung.md).
        NHV_Util.Log(NHV_Cfg_Debug, "StartVeyraTrial: Veyra unavailable, skipping scene")
        Return
    EndIf
    If !VeyraTrialScene
        NHV_Util.Log(NHV_Cfg_Debug, "StartVeyraTrial: VeyraTrialScene property not set in the CK")
        Return
    EndIf
    ; Veyra lives in the Deep Sanctuary; bring her to the camp (the scene has no travel action).
    Actor kVeyra = VeyraAlias.GetActorRef()
    If kVeyra.IsDead() || kVeyra.IsDisabled()
        NHV_Util.Log(NHV_Cfg_Debug, "StartVeyraTrial: Veyra dead or disabled, skipping scene")
        Return
    EndIf
    If VeyraTrialMarker
        kVeyra.MoveTo(VeyraTrialMarker)
    ElseIf CampMarker
        kVeyra.MoveTo(CampMarker, 0.0, 256.0, 0.0)
        NHV_Util.Log(NHV_Cfg_Debug, "StartVeyraTrial: VeyraTrialMarker not set, Veyra placed near CampMarker")
    Else
        NHV_Util.Log(NHV_Cfg_Debug, "StartVeyraTrial: no marker for Veyra, she stays where she is")
    EndIf
    ; The alias package NHV_Pkg_Q01_VeyraTrialHold (stage 50 + this global) keeps her at the marker for the scene.
    If NHV_Q01_TrialActive
        NHV_Q01_TrialActive.SetValueInt(1)
    Else
        NHV_Util.Log(NHV_Cfg_Debug, "StartVeyraTrial: NHV_Q01_TrialActive property not set, Veyra is not held")
    EndIf
    kVeyra.EvaluatePackage()
    LockCutscene(VeyraTrialScene)
    VeyraTrialScene.Start()
EndFunction

Function EndVeyraTrial()
    UnlockCutscene()
    ReleaseVeyraFromTrial()
    If bHrefnaWillKill && !bHrefnaAttacked
        RegisterForSingleUpdate(2.0) ; the trial scene's watchdog chain ended with the unlock: resume the kill watch
    EndIf
    ; Stage stays 50; the Persuade/Intimidate/"Step aside" branch and the Quintus scenes are
    ; dialogue- and package-driven from here (CK), ending in OnQuintusKilled() below.
EndFunction

; The trial is over (or was abandoned): Veyra's hold package ends, she may leave normally.
Function ReleaseVeyraFromTrial()
    If NHV_Q01_TrialActive && NHV_Q01_TrialActive.GetValueInt() != 0
        NHV_Q01_TrialActive.SetValueInt(0)
        If VeyraAlias
            Actor kVeyra = VeyraAlias.GetActorRef()
            If kVeyra
                kVeyra.EvaluatePackage()
            EndIf
        EndIf
        NHV_Util.Log(NHV_Cfg_Debug, "Veyra released from the trial hold")
    EndIf
EndFunction

; ---------------------------------------------------------------------------
; Stage 50: Hrefna kills Quintus herself (Persuade / Intimidate succeeded)
; ---------------------------------------------------------------------------

; Called from the end fragments of the successful Persuade and Intimidate responses. Does not start
; anything by itself: once the flag is set, a distance poll waits until player and Hrefna are near Quintus.
Function HrefnaAgreesToKill()
    If GetStage() != 50 || bHrefnaAttacked
        NHV_Util.Log(NHV_Cfg_Debug, "HrefnaAgreesToKill: ignored (stage " + GetStage() + ")")
        Return
    EndIf
    bHrefnaWillKill = True
    iAttackTries = 0
    NHV_Util.Log(NHV_Cfg_Debug, "HrefnaAgreesToKill: Hrefna will kill Quintus, kill watch running")
    RegisterForSingleUpdate(2.0)
EndFunction

; Called from the "Step aside" response: the player does it, no scene, Trial counts as unproven.
Function PlayerWillKill()
    If bHrefnaAttacked
        Return ; too late, the fight already started
    EndIf
    bHrefnaWillKill = False
    bApproachStarted = False ; a later HrefnaAgreesToKill() starts from scratch (distance check, scene)
    iApproachTicks = 0
    iAttackTries = 0
    NHV_Util.Log(NHV_Cfg_Debug, "PlayerWillKill: kill watch off")
EndFunction

Function KillWatchCheck()
    If GetStage() != 50 || !bHrefnaWillKill || bApproachStarted
        Return
    EndIf
    Actor kPlayer = Game.GetPlayer()
    Actor kQuintus = None
    Actor kHrefna = None
    If QuintusAlias
        kQuintus = QuintusAlias.GetActorRef()
    EndIf
    If HrefnaAlias
        kHrefna = HrefnaAlias.GetActorRef()
    EndIf
    If kQuintus && kQuintus.IsDead()
        Return ; dead: OnQuintusKilled() advances the quest
    EndIf
    If kHrefna && kHrefna.IsDead()
        bHrefnaWillKill = False ; nobody left to do it; the player can still kill him (unproven)
        NHV_Util.Log(NHV_Cfg_Debug, "KillWatchCheck: Hrefna is dead, kill watch off")
        Return
    EndIf
    If kPlayer && kQuintus && kHrefna && !kHrefna.IsDead() && kQuintus.Is3DLoaded() && kHrefna.Is3DLoaded()
        If kPlayer.GetDistance(kQuintus) <= KillApproachRadius && kHrefna.GetDistance(kQuintus) <= KillApproachRadius
            StartQuintusApproach()
            Return
        EndIf
    EndIf
    RegisterForSingleUpdate(3.0) ; not there yet (or Hrefna/Quintus not loaded): keep waiting, cheap
EndFunction

Function StartQuintusApproach()
    bApproachStarted = True
    If !QuintusApproachScene
        NHV_Util.Log(NHV_Cfg_Debug, "StartQuintusApproach: QuintusApproachScene property not set in the CK, attacking without scene")
        HrefnaAttacksQuintus()
        Return
    EndIf
    iApproachTicks = 0
    LockCutscene(QuintusApproachScene)
    QuintusApproachScene.Start()
    RegisterForSingleUpdate(2.0) ; also when no lock was taken: OnUpdate then waits for the scene
EndFunction

; Called from the QuintusApproach scene's end fragment.
Function EndQuintusApproach()
    UnlockCutscene()
    If bHrefnaWillKill
        HrefnaAttacksQuintus()
    EndIf
EndFunction

Function HrefnaAttacksQuintus()
    If bHrefnaAttacked || GetStage() != 50
        Return
    EndIf
    MakeQuintusMortal()
    Actor kHrefna = None
    Actor kQuintus = None
    If HrefnaAlias
        kHrefna = HrefnaAlias.GetActorRef()
    EndIf
    If QuintusAlias
        kQuintus = QuintusAlias.GetActorRef()
    EndIf
    If (kHrefna && kHrefna.IsDead()) || (kQuintus && kQuintus.IsDead())
        bHrefnaWillKill = False ; one of them is dead: nothing to fight (Quintus' death is handled by OnQuintusKilled)
        NHV_Util.Log(NHV_Cfg_Debug, "HrefnaAttacksQuintus: Hrefna or Quintus already dead, giving up")
        Return
    EndIf
    If !kHrefna || !kQuintus || !kHrefna.Is3DLoaded() || !kQuintus.Is3DLoaded()
        iAttackTries += 1
        If iAttackTries > 10
            bHrefnaWillKill = False ; give up quietly; the player can still kill him (unproven)
            bApproachStarted = False
            NHV_Util.Log(NHV_Cfg_Debug, "HrefnaAttacksQuintus: Hrefna or Quintus not available, giving up")
        Else
            RegisterForSingleUpdate(3.0) ; try again (stays in the approach-started branch of OnUpdate)
        EndIf
        Return
    EndIf
    bHrefnaAttacked = True
    fHrefnaAggression = kHrefna.GetActorValue("Aggression")
    kHrefna.GetActorBase().SetProtected(True) ; safety net only: there is no fight any more, see below
    bHrefnaFought = True ; RestoreHrefnaAfterFight() takes the protection off again once Quintus is dead
    HrefnaAssassinatesQuintus(kHrefna, kQuintus)
EndFunction

; Hrefna does not duel Quintus (his axe could kill her and fail the contract): she assassinates him with
; one dagger strike. With HrefnaKillIdle set in the CK a paired kill-move plays first; whatever the
; animation does, Quintus is killed by script afterwards, so the outcome never depends on it.
Bool bAssassinating = False

Function HrefnaAssassinatesQuintus(Actor akHrefna, Actor akQuintus)
    If bAssassinating
        Return ; a load during the strike must not run it twice
    EndIf
    bAssassinating = True
    akQuintus.StopCombat()
    akHrefna.StopCombat() ; an actor in combat refuses PlayIdleWithTarget
    If HrefnaKillIdle
        If akHrefna.PlayIdleWithTarget(HrefnaKillIdle, akQuintus)
            bKillPending = True ; let the strike land: FinishAssassination() runs with the next tick (no Utility.Wait in OnUpdate)
            RequestUpdate(1.5)
            Return
        Else
            NHV_Util.Log(NHV_Cfg_Debug, "HrefnaAssassinatesQuintus: kill-move idle refused, killing without it")
        EndIf
    EndIf
    If !akQuintus.IsDead()
        akQuintus.Kill(akHrefna) ; OnDeath -> OnQuintusKilled(Hrefna): Trial passed
    EndIf
    NHV_Util.Log(NHV_Cfg_Debug, "HrefnaAssassinatesQuintus: Quintus assassinated by Hrefna")
    bAssassinating = False
EndFunction

; Second half of the assassination after the kill-move had time to land (bKillPending, from OnUpdate).
Function FinishAssassination()
    Actor kQuintus = None
    Actor kHrefna = None
    If QuintusAlias
        kQuintus = QuintusAlias.GetActorRef()
    EndIf
    If HrefnaAlias
        kHrefna = HrefnaAlias.GetActorRef()
    EndIf
    If kQuintus && !kQuintus.IsDead()
        kQuintus.Kill(kHrefna)
    EndIf
    NHV_Util.Log(NHV_Cfg_Debug, "HrefnaAssassinatesQuintus: Quintus assassinated by Hrefna")
    bAssassinating = False
EndFunction

; Undo the fight state (aggression, protection, combat). Idempotent; called when Quintus dies and on load.
Function RestoreHrefnaAfterFight()
    If !bHrefnaFought
        Return
    EndIf
    ; The protection lives on the ActorBase (persistent), so take it off even if the alias is already
    ; empty (CompleteRecruitment clears it): NHV_Hrefna is 004007 in this plugin.
    ActorBase kBase = Game.GetFormFromFile(0x004007, "NightsHarvest.esp") as ActorBase
    If kBase
        kBase.SetProtected(False)
    EndIf
    Actor kHrefna = None
    If HrefnaAlias
        kHrefna = HrefnaAlias.GetActorRef()
    EndIf
    If kHrefna
        kHrefna.StopCombat()
        kHrefna.StopCombatAlarm()
        kHrefna.SetActorValue("Aggression", fHrefnaAggression)
        kHrefna.EvaluatePackage()
    EndIf
    If kBase
        bHrefnaFought = False ; only forget the fight state once the protection is really gone
        NHV_Util.Log(NHV_Cfg_Debug, "RestoreHrefnaAfterFight: Hrefna calm again")
    Else
        NHV_Util.Log(NHV_Cfg_Debug, "RestoreHrefnaAfterFight: NHV_Hrefna base not found, will retry on load")
    EndIf
EndFunction

; ---------------------------------------------------------------------------
; Stage 50 -> 60: Quintus dies
; ---------------------------------------------------------------------------

; Called by NHV_Q01_QuintusAliasScript.OnDeath(), regardless of which scene/variant played or who
; struck the killing blow.
Function OnQuintusKilled(Actor akKiller)
    RestoreHrefnaAfterFight() ; before the stage guards: also undoes a fight state left by an odd death
    If GetStage() < 40 || GetStage() >= 60
        Return ; too early (unscripted death, see docs/plan section 10) or already handled
    EndIf
    If akKiller == Game.GetPlayer() && NHV_Flag_HrefnaUnproven
        NHV_Flag_HrefnaUnproven.SetValueInt(1) ; player did the killing herself: Trial not passed
    EndIf
    ; Enhanced dialogue: Hrefna's papers conversation (a Hello topic) waits on the cursor
    StockQuintusBody()
    AdvanceToPapers()
EndFunction

; ---------------------------------------------------------------------------
; Enhanced arc (E45): world events called by the dialogue fragments. Everything placed in the CK is optional here:
; a property left empty is logged and skipped. See docs/ck/M1.7-Q01-Enhanced-CK-Anleitung.md.
; ---------------------------------------------------------------------------
ObjectReference Property FarmMapMarker Auto        ; map marker "Stormhollow Farm" (initially disabled)
ObjectReference Property WatchpostMapMarker Auto   ; map marker "Old Watchpost" (initially disabled)
ObjectReference Property CampMapMarker Auto        ; map marker "Hrefna's Camp" (initially disabled)
ObjectReference Property QuintusInnSpot Auto       ; where Quintus stands in the inn when he is brought back
ObjectReference Property QuintusFarmSpot Auto      ; where Quintus waits at the farm
ObjectReference Property HrefnaFarmSpot Auto       ; where Hrefna goes when she gives herself up
ObjectReference[] Property ScavengerRefs Auto      ; the marsh scavengers at the reedbed (all become hostile together)
ObjectReference[] Property SoldierRefs Auto        ; the soldiers at the old watchpost
ReferenceAlias Property ScoutAlias Auto            ; alias 6, the Oculatus scout

Bool bWatchpostWatch = False
Int iPendingScene = 0
Bool bVeyraWatch = False   ; stages 20-69: Veyra joins the player at the farm and catches up when left behind
Bool bVeyraJoined = False  ; she has arrived at the player once

Function DelayScene(Int aiSceneID, Float afDelay)
    iPendingScene = aiSceneID
    RegisterForSingleUpdate(afDelay)
EndFunction

; The single update timer is shared by the camp poll, the watchpost watch, the homecoming watch, delayed scenes and the
; cutscene watchdog: after a branch that returns early, wake up again for whatever else is waiting (also after a load).
Function RearmWatches()
    If bWatchpostWatch || bVeyraWatch || bDebriefWatch || bTableCursorPending || bHomeWatch || bCampWatchStarted || iPendingScene != 0 || bReedbedWatch || bReedFightPending || bDeathWatch || bKillPending || IsCutsceneLocked()
        RegisterForSingleUpdate(2.5)
    EndIf
EndFunction

; ---------------------------------------------------------------------------
; Reedbed fight (ingame test 02.10.2026, feedback 3-6): the talk ends with a fight, the sack is not lootable before the fight
; is over. Everything runs through the one shared update timer (OnUpdate / RearmWatches), nothing here owns a timer.
; ---------------------------------------------------------------------------
ObjectReference Property ReedbedSack Auto   ; optional: NHV_Cont_Q01_ReedbedSack ref (0x0089E1); None = looked up by FormID
Bool bReedFightPending = False   ; the last scavenger line ended: the fight starts with the next tick (never inside the dialogue)
Bool bReedFightStarted = False
Bool bReedbedWatch = False
Bool bReedbedLootReleased = False
Int iReedbedTicks = 0            ; ticks without any scavenger in combat after the fight began (flee / lost-track timeout)
Float fTimerDue = 0.0            ; real-time second the shared update timer is due (RequestUpdate only; 0 = none pending)
Bool bKillPending = False        ; Hrefna's kill-move was played: Quintus dies with the next tick (replaces Utility.Wait)
Bool bScavNoteGiven = False
Bool bScavTuned = False          ; Aggression/Confidence of the scavengers were raised for the fight
Float fScavAggression = 0.0
Float fScavConfidence = 0.0
Float fReedbedIdleSince = 0.0    ; game time (days) since when no scavenger has fought; 0 = fighting or not started
Bool bDeathWatch = False         ; stage 10-69: Hakan / Hrefna died before their dialogue was over (feedback 6)
Bool bHakanDeathHandled = False
Bool bHrefnaDeathHandled = False

; Asks for an update in afSeconds without ever pushing back a nearer one (RegisterForSingleUpdate overwrites): the watches
; of this feature use it so that one never shortens or lengthens the wait of another.
Function RequestUpdate(Float afSeconds)
    Float fNow = Utility.GetCurrentRealTime()
    If fTimerDue > fNow && fTimerDue - fNow <= afSeconds
        Return ; an update that comes sooner is pending already
    EndIf
    fTimerDue = fNow + afSeconds
    RegisterForSingleUpdate(afSeconds)
EndFunction

Actor Function GetScavenger(Int aiIndex)
    Actor kScav = None
    If ScavengerRefs && aiIndex < ScavengerRefs.Length
        kScav = ScavengerRefs[aiIndex] as Actor
    EndIf
    If !kScav
        Int iId = 0x0089E3 ; NHV_Ref_Q01_Scav01
        If aiIndex == 1
            iId = 0x0089E4 ; Scav03
        ElseIf aiIndex == 2
            iId = 0x0089E2 ; Scav02
        EndIf
        kScav = Game.GetFormFromFile(iId, "NightsHarvest.esp") as Actor
    EndIf
    Return kScav
EndFunction

ObjectReference Function GetReedbedSack()
    ObjectReference kSack = ReedbedSack
    If !kSack
        kSack = Game.GetFormFromFile(0x0089E1, "NightsHarvest.esp") as ObjectReference
    EndIf
    Return kSack
EndFunction

; True while the sack may be opened: before the quest reaches the reedbed, after the fight, and once the quest is past stage 19.
Bool Function IsReedbedLootFree()
    Int iStage = GetStage()
    Return bReedbedLootReleased || iStage < 10 || iStage >= 20
EndFunction

Function LockReedbedSack()
    If IsReedbedLootFree()
        Return
    EndIf
    ObjectReference kSack = GetReedbedSack()
    If kSack
        kSack.BlockActivation(True)
    EndIf
EndFunction

Function ReleaseReedbedSack()
    bReedbedLootReleased = True
    bReedbedWatch = False
    RestoreScavengers()
    ObjectReference kSack = GetReedbedSack()
    If kSack
        kSack.BlockActivation(False)
    EndIf
    NHV_Util.Log(NHV_Cfg_Debug, "Reedbed: the sack can be looted now")
EndFunction

; Called by the sack's script (CK, optional), by OnContractLoadGame and by ReedbedHostile: lock the sack and watch the scavengers.
Function BeginReedbedWatch()
    If bReedbedLootReleased || IsReedbedLootFree()
        Return
    EndIf
    LockReedbedSack()
    If !bReedbedWatch
        bReedbedWatch = True
        RequestUpdate(4.0)
    EndIf
EndFunction

; The talk is over: the scavengers attack (started from OnUpdate, a moment after the dialogue has closed).
Function ReedbedHostile()
    bReedFightStarted = True
    iReedbedTicks = 0
    fReedbedIdleSince = 0.0
    BeginReedbedWatch()
    bReedFightPending = True
    RequestUpdate(1.5)
    NHV_Util.Log(NHV_Cfg_Debug, "Reedbed: the scavengers will attack in a moment")
EndFunction

; The fight is over: surviving scavengers get their old Aggression/Confidence back.
Function RestoreScavengers()
    If !bScavTuned
        Return
    EndIf
    bScavTuned = False
    Int i = 0
    While i < 3
        Actor kScav = GetScavenger(i)
        If kScav && !kScav.IsDead()
            kScav.SetActorValue("Aggression", fScavAggression)
            kScav.SetActorValue("Confidence", fScavConfidence)
        EndIf
        i += 1
    EndWhile
EndFunction

Function ReedbedStartFight()
    Actor kPlayer = Game.GetPlayer()
    Int i = 0
    While i < 3
        Actor kScav = GetScavenger(i)
        If kScav && !kScav.IsDead() && !kScav.IsDisabled()
            If !bScavTuned
                bScavTuned = True
                fScavAggression = kScav.GetActorValue("Aggression")
                fScavConfidence = kScav.GetActorValue("Confidence")
            EndIf
            kScav.SetActorValue("Aggression", 2.0)  ; very aggressive: a default (unaggressive) scavenger may flee instead
            kScav.SetActorValue("Confidence", 4.0)  ; foolhardy: they stand and fight
            kScav.StartCombat(kPlayer)
            kScav.EvaluatePackage()
        EndIf
        i += 1
    EndWhile
    NHV_Util.Log(NHV_Cfg_Debug, "Reedbed: scavengers turn hostile")
EndFunction

; Releases the sack when every scavenger is dead or disabled, or when nobody has fought for about two minutes (they fled).
Function ReedbedWatchTick()
    If bReedbedLootReleased || GetStage() >= 20
        If !bReedbedLootReleased
            ReleaseReedbedSack()
        EndIf
        bReedbedWatch = False
        Return
    EndIf
    Int iAlive = 0
    Int iFighting = 0
    Int i = 0
    While i < 3
        Actor kScav = GetScavenger(i)
        If kScav
            If kScav.IsDead()
                If !bScavNoteGiven
                    bScavNoteGiven = True
                    EnsureNote(kScav, 0x00AD43)
                EndIf
            ElseIf !kScav.IsDisabled()
                iAlive += 1
                If kScav.IsInCombat()
                    iFighting += 1
                EndIf
            EndIf
        EndIf
        i += 1
    EndWhile
    If iAlive == 0
        ReleaseReedbedSack()
        Return
    EndIf
    If bReedFightStarted && !bReedFightPending
        Float fNow = Utility.GetCurrentGameTime()
        If iFighting > 0
            fReedbedIdleSince = 0.0
        ElseIf fReedbedIdleSince <= 0.0 || fReedbedIdleSince > fNow
            fReedbedIdleSince = fNow
        Else
            If fNow - fReedbedIdleSince > 0.05 ; about 1.2 game hours without a fight (a few real minutes at the default timescale)
                NHV_Util.Log(NHV_Cfg_Debug, "Reedbed: the surviving scavengers gave up the fight")
                ReleaseReedbedSack()
            EndIf
        EndIf
    EndIf
EndFunction

; Fallback note (feedback 6): the NPC carries the clue of the dialogue he did not get to finish. New games get it from the
; base inventory (NPC record); this adds it to saves whose actors were spawned earlier. Never twice.
Function EnsureNote(Actor akActor, Int aiNoteID)
    If !akActor
        Return
    EndIf
    Form kNote = Game.GetFormFromFile(aiNoteID, "NightsHarvest.esp")
    If kNote && akActor.GetItemCount(kNote) == 0 && Game.GetPlayer().GetItemCount(kNote) == 0
        akActor.AddItem(kNote, 1, True)
    EndIf
EndFunction

Actor Function GetHakan()
    Actor kHakan = None
    If HakanAlias
        kHakan = HakanAlias.GetActorRef()
    EndIf
    If !kHakan
        kHakan = Game.GetFormFromFile(0x0048A6, "NightsHarvest.esp") as Actor ; NHV_HakanRef
    EndIf
    Return kHakan
EndFunction

Actor Function GetHrefna()
    Actor kHrefna = None
    If HrefnaAlias
        kHrefna = HrefnaAlias.GetActorRef()
    EndIf
    If !kHrefna
        kHrefna = Game.GetFormFromFile(0x004981, "NightsHarvest.esp") as Actor ; NHV_HrefnaRef
    EndIf
    Return kHrefna
EndFunction

Function ArmDeathWatch()
    Int iStage = GetStage()
    If bDeathWatch || iStage < 10 || iStage >= 70
        Return
    EndIf
    bDeathWatch = True
    RequestUpdate(5.0)
EndFunction

; Stage 10-69: a dead Hakan or Hrefna must not leave the quest without a way forward.
Function DeathWatchTick()
    Int iStage = GetStage()
    If iStage < 10 || iStage >= 70
        bDeathWatch = False
        Return
    EndIf
    If !bHakanDeathHandled && iStage < 20
        Actor kHakan = GetHakan()
        If kHakan && kHakan.IsDead()
            HandleHakanDeath(kHakan)
        EndIf
    EndIf
    If !bHrefnaDeathHandled && iStage >= 46
        Actor kHrefna = GetHrefna()
        If kHrefna && kHrefna.IsDead()
            HandleHrefnaDeath(kHrefna)
        EndIf
    EndIf
EndFunction

; Hakan died before he named his suspect (stage 10-19): his notes carry the clue, the farm appears on the map and the
; quest moves on exactly as after the marker handover (same calls as the end of the hret topic, TIF__02007146).
Function HandleHakanDeath(Actor akHakan)
    bHakanDeathHandled = True
    EnsureNote(akHakan, 0x00AD40)
    If GetStage() >= 20 || NHV_Util.FlowGet(0x00711D) == 1
        Return
    EndIf
    NHV_Util.Log(NHV_Cfg_Debug, "Hakan died before his talk was over: farm marker and stage 20 by script, notes on the body")
    NHV_Util.FlowSet(0x00711D, 1)
    ReleaseReedbedSack()
    OnMarkerReturned()
    NHV_Util.FlowObjective(0x004000, 9003, 9004)
    NHV_Util.FlowStage(0x004000, 20)
    NHV_Util.FlowSet(0x007000, 0)
    NHV_Util.FlowSet(0x007001, 43)
EndFunction

; Hrefna died before the judgement (stage 20-69): the outcome is "killed", the debrief at stage 100 takes over, and her
; confession lies on the body. The fragment is handed over so the debrief condition (fragment in the inventory) holds.
Function HandleHrefnaDeath(Actor akHrefna)
    bHrefnaDeathHandled = True
    EnsureNote(akHrefna, 0x00AD41)
    If GetStage() >= 70
        Return
    EndIf
    If NHV_Status_Hrefna
        Int iCurrent = NHV_Status_Hrefna.GetValueInt()
        If iCurrent == STATUS_RECRUITED || iCurrent == STATUS_RELEASED || iCurrent == STATUS_SPECIAL
            Return
        EndIf
        NHV_Status_Hrefna.SetValueInt(STATUS_KILLED)
    EndIf
    If GetStage() < 46
        Return
    EndIf
    NHV_Util.Log(NHV_Cfg_Debug, "Hrefna died before the judgement: outcome killed, quest moves to stage 100")
    ; clean up what stage 46-69 may have left running before the jump
    UnlockCutscene()
    ReleaseVeyraFromTrial()
    If VeyraTrialScene && VeyraTrialScene.IsPlaying()
        VeyraTrialScene.Stop()
    EndIf
    If QuintusApproachScene && QuintusApproachScene.IsPlaying()
        QuintusApproachScene.Stop()
    EndIf
    SetQuintusAtFarm(False)
    bHrefnaWillKill = False
    Int iObj = 9001
    While iObj <= 9019
        If IsObjectiveDisplayed(iObj) && !IsObjectiveCompleted(iObj)
            SetObjectiveCompleted(iObj)
        EndIf
        iObj += 1
    EndWhile
    GiveOculatusFragment()
    SetStage(100)
EndFunction

; Q01 hooks the Stage 10 start fragment (it calls FillVeyraAlias()) to arm the death watch without touching the fragment.
Function FillVeyraAlias()
    Parent.FillVeyraAlias()
    ArmDeathWatch()
EndFunction

; Hakan takes the red ferry marker: the item leaves the inventory, the farm appears on the map.
Function OnMarkerReturned()
    Form kItem = Game.GetFormFromFile(0x007F24, "NightsHarvest.esp")
    Actor kPlayer = Game.GetPlayer()
    If kItem && kPlayer.GetItemCount(kItem) > 0
        kPlayer.RemoveItem(kItem, kPlayer.GetItemCount(kItem), True)
    EndIf
    EnableMarker(1)
    BeginVeyraWatch()
EndFunction

; Stage 20-69: Veyra lives in the Deep Sanctuary, so nothing but a script brings her to the player. She steps in behind the player
; when the farm comes close (or the player stands in its cell) and catches up again whenever she is left behind (fast travel, doors).
Function BeginVeyraWatch()
    If bVeyraWatch
        Return
    EndIf
    bVeyraWatch = True
    FillVeyraAlias()
    RegisterForSingleUpdate(3.0)
    NHV_Util.Log(NHV_Cfg_Debug, "Veyra watch started")
EndFunction

Function VeyraTick()
    Int iStage = GetStage()
    If iStage < 20 || iStage >= 70
        bVeyraWatch = False
        If iStage < 20
            bVeyraJoined = False ; quest reset: she joins at the farm again
            SetQuintusAtFarm(False)
        EndIf
        Return
    EndIf
    If IsCutsceneLocked()
        Return
    EndIf
    Actor kPlayer = Game.GetPlayer()
    If !VeyraAlias || !VeyraAlias.GetActorRef()
        FillVeyraAlias()
    EndIf
    Actor kVeyra = None
    If VeyraAlias
        kVeyra = VeyraAlias.GetActorRef()
    EndIf
    If !kVeyra || kVeyra.IsDead() || kVeyra.IsDisabled()
        Return
    EndIf
    Bool bNear = kVeyra.Is3DLoaded() && kPlayer.GetDistance(kVeyra) < 2500.0
    If !bVeyraJoined
        Cell kFarm = Game.GetFormFromFile(0x0048A8, "NightsHarvest.esp") as Cell
        Bool bAtFarm = kFarm && kPlayer.GetParentCell() == kFarm
        If !bAtFarm && FarmMapMarker && kPlayer.GetParentCell() == FarmMapMarker.GetParentCell()
            bAtFarm = kPlayer.GetDistance(FarmMapMarker) < 3500.0
        EndIf
        If !bAtFarm
            Return
        EndIf
    ElseIf bNear || kPlayer.IsInCombat()
        Return ; close enough, or never pull her around mid-fight
    EndIf
    Float fAngle = kPlayer.GetAngleZ()
    kVeyra.MoveTo(kPlayer, -300.0 * Math.Sin(fAngle), -300.0 * Math.Cos(fAngle), 0.0)
    kVeyra.EvaluatePackage()
    bVeyraJoined = True
    NHV_Util.Log(NHV_Cfg_Debug, "Veyra steps in beside the player")
EndFunction

; End of the scout conversation: the camp appears on the map and the quest moves on to stage 30, where the camp poll waits for the player.
Function GoToCamp()
    EnableMarker(3)
    If GetStage() < 30
        SetStage(30)
    EndIf
EndFunction

; The player hands Hrefna the letter to the daughter: it leaves the inventory just before she reacts to it (she has read it).
Function TakeLetter()
    Form kLetter = Game.GetFormFromFile(0x007F10, "NightsHarvest.esp")
    Actor kPlayer = Game.GetPlayer()
    If kLetter && kPlayer.GetItemCount(kLetter) > 0
        kPlayer.RemoveItem(kLetter, kPlayer.GetItemCount(kLetter), True)
        NHV_Util.Log(NHV_Cfg_Debug, "TakeLetter: the letter went to Hrefna")
    EndIf
EndFunction

; Q01 -> Q02 transition (end of the debrief): Veyra goes to the map table in the Ledger Room and greets the player there once;
; the table itself (NHV_MapTableScript, Q01 stage 100 unlocks it) starts the next contract. Idempotent.
Bool bTableOpened = False
Bool bTableCursorPending = False ; the debrief chain resets the cursor right after OpenMapTable(): the greeting is armed a moment later
Bool bDebriefWatch = False ; stage 100 until the debrief ended: Veyra comes to the player inside the sanctuary cells (no console search)

Function BeginDebriefWatch()
    If bDebriefWatch || bTableOpened
        Return
    EndIf
    bDebriefWatch = True
    RegisterForSingleUpdate(4.0)
    NHV_Util.Log(NHV_Cfg_Debug, "Debrief watch started")
EndFunction

; The debrief is Veyra's Hello. Wherever the script left her (the return marker is an exterior spot in Dawnstar), she steps in front
; of the player as soon as he stands in the Dawnstar Sanctuary or the Deep Sanctuary and she is not close.
Function DebriefTick()
    If GetStage() < 100 || bTableOpened
        bDebriefWatch = False
        Return
    EndIf
    Actor kPlayer = Game.GetPlayer()
    Cell kCell = kPlayer.GetParentCell()
    Cell kDawnstar = Game.GetFormFromFile(0x0193EE, "Skyrim.esm") as Cell
    Cell kDeep = Game.GetFormFromFile(0x001342, "NightsHarvest.esp") as Cell
    If !kCell || (kCell != kDawnstar && kCell != kDeep)
        Return
    EndIf
    Actor kVeyra = None
    If Core
        kVeyra = Core.GetVeyraActor()
    EndIf
    If !kVeyra || kVeyra.IsDead()
        Return
    EndIf
    If kVeyra.IsDisabled()
        kVeyra.Enable()
    EndIf
    If kVeyra.Is3DLoaded() && kPlayer.GetDistance(kVeyra) < 1500.0
        Return
    EndIf
    Float fAngle = kPlayer.GetAngleZ()
    kVeyra.MoveTo(kPlayer, 350.0 * Math.Sin(fAngle), 350.0 * Math.Cos(fAngle), 0.0)
    kVeyra.SetDontMove(True) ; hold her until the debrief is over (she walked off to her own package before)
    kVeyra.EvaluatePackage()
    NHV_Util.Log(NHV_Cfg_Debug, "DebriefTick: Veyra steps in front of the player")
EndFunction

Function OpenMapTable()
    If bTableOpened
        Return
    EndIf
    bTableOpened = True
    ObjectReference kTable = Game.GetFormFromFile(0x005ECD, "NightsHarvest.esp") as ObjectReference ; NHV_Mk_MapTable_Veyra
    Actor kVeyra = None
    If Core
        kVeyra = Core.GetVeyraActor()
    EndIf
    If kVeyra && kTable && !kVeyra.IsDead() && !kVeyra.IsDisabled()
        kVeyra.SetDontMove(False) ; she was held for the debrief
        kVeyra.MoveTo(kTable)
        kVeyra.EvaluatePackage()
        NHV_Util.Log(NHV_Cfg_Debug, "OpenMapTable: Veyra waits at the map table")
    Else
        NHV_Util.Log(NHV_Cfg_Debug, "OpenMapTable: Veyra or the table marker is missing")
    EndIf
    bTableCursorPending = True
    RegisterForSingleUpdate(2.0)
    Debug.Notification("Veyra waits at the map table in the Ledger Room.")
EndFunction

; Fallback to the map table menu: "Windhelm" is the first pin (button 0 -> Q02), started exactly like the table does it.
Function StartQ02FromTable()
    NHV_MapTableScript kTable = Game.GetFormFromFile(0x005ECC, "NightsHarvest.esp") as NHV_MapTableScript ; NHV_Ref_MapTable
    If kTable
        kTable.Choose(2)
    Else
        NHV_Util.Log(NHV_Cfg_Debug, "StartQ02FromTable: the map table script is not reachable")
    EndIf
EndFunction

Function EnableMarker(Int aiWhich)
    ObjectReference kMarker = None
    If aiWhich == 1
        kMarker = FarmMapMarker
    ElseIf aiWhich == 2
        kMarker = WatchpostMapMarker
    ElseIf aiWhich == 3
        kMarker = CampMapMarker
    EndIf
    If kMarker
        kMarker.Enable()
        NHV_Util.Log(NHV_Cfg_Debug, "Map marker " + aiWhich + " enabled")
    Else
        NHV_Util.Log(NHV_Cfg_Debug, "EnableMarker " + aiWhich + ": property not set in the CK")
    EndIf
EndFunction

; Stage 25: as soon as every soldier is dead the scout stops fighting and can be questioned.
Function BeginWatchpostWatch()
    If bWatchpostWatch
        Return
    EndIf
    bWatchpostWatch = True
    MakeScoutSafe()
    RegisterForSingleUpdate(3.0)
EndFunction

; The scout must survive the fight: he never takes part in it and cannot die (ingame test 01.10.2026: he fought the
; player and died, so nobody could be questioned). Essential persists on the base record, additive and idempotent.
Int Property FLOW_CURSOR_SCOUT = 28956 AutoReadOnly ; NHV_Q01V2_CursorScout (0x00711C): 49 = scout hub open

; The scout actor: the alias, or (alias still empty, e.g. the placed ref was not loaded when the quest started) the placed ref
; 0x0089F7 NHV_Ref_Q01_Scout, which then fills the alias. None only when the ref does not exist at all.
Actor Function GetScout()
    Actor kScout = None
    If ScoutAlias
        kScout = ScoutAlias.GetActorRef()
    EndIf
    If !kScout
        kScout = Game.GetFormFromFile(0x0089F7, "NightsHarvest.esp") as Actor
        If kScout && ScoutAlias
            ScoutAlias.ForceRefTo(kScout)
            NHV_Util.Log(NHV_Cfg_Debug, "GetScout: the scout alias was empty, filled from the placed ref")
        EndIf
    EndIf
    Return kScout
EndFunction

; Stage 25: the scout hub needs the scout cursor on 49..51 (49 is set at the end of the boot-print talk); repair a stale value.
Function EnsureScoutCursor()
    If GetStage() != 25
        Return
    EndIf
    Int iCur = NHV_Util.FlowGet(FLOW_CURSOR_SCOUT)
    If iCur < 49 || iCur > 51
        NHV_Util.FlowSet(FLOW_CURSOR_SCOUT, 49)
        NHV_Util.Log(NHV_Cfg_Debug, "EnsureScoutCursor: scout cursor was " + iCur + ", reset to 49")
    EndIf
EndFunction

Function MakeScoutSafe()
    Actor kScout = GetScout()
    If kScout
        kScout.GetActorBase().SetEssential(True)
        kScout.SetGhost(False) ; a ghost cannot be addressed (see Lucien): clear it in saves that got it from the previous build
        kScout.SetActorValue("Aggression", 0.0)
    Else
        NHV_Util.Log(NHV_Cfg_Debug, "MakeScoutSafe: the scout alias is not filled")
    EndIf
EndFunction

Bool bWatchpostAggro = False

; Soldiers and scout turn on the player when he comes close (no faction needed in the CK).
Function WatchpostAggro(Actor akPlayer)
    bWatchpostAggro = True
    Int i = 0
    While SoldierRefs && i < SoldierRefs.Length
        Actor kSoldier = SoldierRefs[i] as Actor
        If kSoldier && !kSoldier.IsDead()
            kSoldier.StartCombat(akPlayer)
        EndIf
        i += 1
    EndWhile
    MakeScoutSafe() ; the scout stays out of the fight
    NHV_Util.Log(NHV_Cfg_Debug, "Watchpost: the garrison attacks")
EndFunction

Function WatchpostCheck()
    Bool bAllDead = True
    Int iValid = 0
    Int j = 0
    While SoldierRefs && j < SoldierRefs.Length
        If SoldierRefs[j]
            iValid += 1
        EndIf
        j += 1
    EndWhile
    If iValid == 0
        ; the CK properties are not filled yet: do not soft-lock the quest, let the scout answer at once
        NHV_Util.Log(NHV_Cfg_Debug, "WatchpostCheck: SoldierRefs empty (CK property not set), the scout yields now")
        bWatchpostWatch = False
        ScoutYields()
        Return
    EndIf
    If !bWatchpostAggro && SoldierRefs && SoldierRefs.Length > 0 && SoldierRefs[0]
        Actor kPlayer = Game.GetPlayer()
        If kPlayer.GetParentCell() == SoldierRefs[0].GetParentCell() && kPlayer.GetDistance(SoldierRefs[0]) < 1500.0
            WatchpostAggro(kPlayer)
        EndIf
    EndIf
    Int i = 0
    While SoldierRefs && i < SoldierRefs.Length
        Actor kSoldier = SoldierRefs[i] as Actor
        If kSoldier && !kSoldier.IsDead()
            bAllDead = False
        EndIf
        i += 1
    EndWhile
    If bAllDead
        bWatchpostWatch = False
        ScoutYields()
    Else
        RegisterForSingleUpdate(3.0)
    EndIf
EndFunction

Function ScoutYields()
    Actor kScout = GetScout()
    If kScout && !kScout.IsDead()
        kScout.StopCombat()
        kScout.StopCombatAlarm()
        kScout.SetGhost(False)
        kScout.SetActorValue("Aggression", 0.0)
        kScout.RestoreActorValue("Health", 1000.0) ; get him out of bleedout quickly so he can be addressed
        kScout.EvaluatePackage()
        EnsureScoutCursor()
    Else
        ; no scout to question (dead or never filled): do not soft-lock, skip his conversation and send the player to the camp
        NHV_Util.Log(NHV_Cfg_Debug, "ScoutYields: the scout is missing or dead, skipping to the camp")
        EnableMarker(3)
        If GetStage() < 30
            SetStage(30)
        EndIf
        Return
    EndIf
    ; (the old scoutYield flag is not used any more: the scout talk is a hub that is always available at stage 25)
    NHV_Util.Log(NHV_Cfg_Debug, "Watchpost cleared, the scout can be questioned")
EndFunction

Function QuintusToInn()
    MakeQuintusMortal()
    SetQuintusAtFarm(False)
    MoveQuintus(QuintusInnSpot, "inn")
EndFunction

Function QuintusToFarm()
    SetQuintusAtFarm(True) ; before the move: also valid when Quintus is not available (Hrefna still waits on the farm)
    MoveQuintus(QuintusFarmSpot, "farm")
EndFunction

; Global 0xAD20 (NHV_Q01_QuintusAtFarm, 1 = Quintus waits on the farm) is the condition of NHV_Pkg_Q01_QuintusFarmHold and
; NHV_Pkg_Q01_HrefnaFarmWaitDay/Night. Looked up by FormID (no CK property needed). Reset to 0 whenever the quest is before stage 45.
Function SetQuintusAtFarm(Bool abAtFarm)
    GlobalVariable kAtFarm = Game.GetFormFromFile(0x00AD20, "NightsHarvest.esp") as GlobalVariable
    If !kAtFarm
        NHV_Util.Log(NHV_Cfg_Debug, "SetQuintusAtFarm: global NHV_Q01_QuintusAtFarm (0xAD20) missing, Quintus and Hrefna farm packages keep the old state")
        Return
    EndIf
    Int iNew = 0
    If abAtFarm
        iNew = 1
    EndIf
    If kAtFarm.GetValueInt() != iNew
        kAtFarm.SetValueInt(iNew)
        NHV_Util.Log(NHV_Cfg_Debug, "SetQuintusAtFarm: " + iNew)
    EndIf
EndFunction

Function MoveQuintus(ObjectReference akSpot, String asWhere)
    Actor kQuintus = None
    If QuintusAlias
        kQuintus = QuintusAlias.GetActorRef()
    EndIf
    If !kQuintus || kQuintus.IsDead()
        Return
    EndIf
    If akSpot
        If kQuintus.IsDisabled()
            kQuintus.Enable()
        EndIf
        kQuintus.MoveTo(akSpot)
        kQuintus.EvaluatePackage()
        NHV_Util.Log(NHV_Cfg_Debug, "Quintus moved to the " + asWhere)
    Else
        NHV_Util.Log(NHV_Cfg_Debug, "MoveQuintus: spot for the " + asWhere + " not set in the CK")
    EndIf
EndFunction

; Branch "Hrefna kills": the death is handled by OnQuintusKilled(), which moves the story to the papers.
Function HrefnaKillsQuintus()
    Actor kHrefna = None
    Actor kQuintus = None
    If HrefnaAlias
        kHrefna = HrefnaAlias.GetActorRef()
    EndIf
    If QuintusAlias
        kQuintus = QuintusAlias.GetActorRef()
    EndIf
    If !kHrefna || !kQuintus || kHrefna.IsDead() || kQuintus.IsDead()
        NHV_Util.Log(NHV_Cfg_Debug, "HrefnaKillsQuintus: Hrefna or Quintus not available")
        Return
    EndIf
    MakeQuintusMortal()
    bHrefnaAttacked = True
    bHrefnaFought = True
    kHrefna.GetActorBase().SetProtected(True)
    HrefnaAssassinatesQuintus(kHrefna, kQuintus)
EndFunction

; Branch "Hrefna surrenders": both leave for the farm, the papers conversation follows there.
Function CaptureOutcome()
    Actor kHrefna = None
    If HrefnaAlias
        kHrefna = HrefnaAlias.GetActorRef()
    EndIf
    If kHrefna && HrefnaFarmSpot
        kHrefna.MoveTo(HrefnaFarmSpot)
        kHrefna.EvaluatePackage()
    Else
        NHV_Util.Log(NHV_Cfg_Debug, "CaptureOutcome: Hrefna or the farm spot is missing")
    EndIf
    QuintusToFarm()
    If kHrefna
        kHrefna.EvaluatePackage() ; the farm wait package of Hrefna depends on the global QuintusToFarm() just set
    EndIf
    If NHV_Flag_HrefnaUnproven
        NHV_Flag_HrefnaUnproven.SetValueInt(1)
    EndIf
    StockQuintusBody() ; the papers conversation needs the dispatch even though Quintus lives
    AdvanceToPapers()
EndFunction

; Branch "the Listener kills": Quintus turns on the player at the farm.
Function QuintusHostile()
    Actor kQuintus = None
    If QuintusAlias
        kQuintus = QuintusAlias.GetActorRef()
    EndIf
    If kQuintus && !kQuintus.IsDead()
        MakeQuintusMortal()
        kQuintus.StartCombat(Game.GetPlayer())
    EndIf
EndFunction

; Stage 60 and the papers conversation (Hrefna speaks first when the player talks to her).
Function AdvanceToPapers()
    If GetStage() < 60
        SetStage(60)
    EndIf
    NHV_Util.FlowSet(FLOW_CURSOR_MAIN, FLOW_ENTRY_PAPERS)
EndFunction

; ---------------------------------------------------------------------------
; Homecoming (V2): after "Recruit" Hrefna stands in the Kitchen; the first time the player comes near her there,
; Nazir and Hrefna meet him in scene NHV_Scn_Q01_04Home (0x7F01). Armed by NHV_CoreScript.OnEnterDeepSanctuary().
; ---------------------------------------------------------------------------
Bool bHomeScenePlayed = False
Bool bHomeWatch = False

Function ArmHomeWatch()
    If bHomeScenePlayed || bHomeWatch || GetStage() < 100 || !NHV_Status_Hrefna
        Return
    EndIf
    If NHV_Status_Hrefna.GetValueInt() != STATUS_RECRUITED
        Return
    EndIf
    bHomeWatch = True
    RegisterForSingleUpdate(3.0)
EndFunction

Function HomeWatchCheck()
    Actor kPlayer = Game.GetPlayer()
    Actor kHrefna = None
    If HrefnaFamilySlotAlias
        kHrefna = HrefnaFamilySlotAlias.GetActorRef()
    EndIf
    If bHomeScenePlayed || !KitchenMarker || !kPlayer || !kHrefna || kHrefna.IsDead()
        bHomeWatch = False
        Return
    EndIf
    If kPlayer.GetParentCell() != KitchenMarker.GetParentCell()
        bHomeWatch = False ; the player left the Deep Sanctuary: the next entry arms the watch again
        Return
    EndIf
    Scene kScene = Game.GetFormFromFile(0x007F01, "NightsHarvest.esp") as Scene
    If kScene && !kScene.IsPlaying() && !kPlayer.IsInCombat() && kPlayer.GetDistance(KitchenMarker) <= 600.0 && kHrefna.Is3DLoaded()
        bHomeScenePlayed = True
        bHomeWatch = False
        kScene.Start()
        NHV_Util.Log(NHV_Cfg_Debug, "Q01 homecoming scene started")
    Else
        RegisterForSingleUpdate(3.0) ; not there yet, busy, or in combat: try again
    EndIf
EndFunction

; Called from the Stage 60 fragment when the player searches Quintus' belongings.
Function GiveOculatusFragment()
    GiveFragmentIfMissing(None, OculatusFragment1)
EndFunction

; ---------------------------------------------------------------------------
; Stage 70: Judgement
; ---------------------------------------------------------------------------
; All three functions guard on GetStage() == 70 so a doubled dialogue callback (e.g. the topic
; fires twice from a fast double-click) can never run the outcome twice.

Function JudgeRecruit()
    If GetStage() != 70
        Return
    EndIf
    If !HrefnaAlias
        NHV_Util.Log(NHV_Cfg_Debug, "JudgeRecruit: HrefnaAlias property not set in the CK")
        Return
    EndIf
    Actor kHrefna = HrefnaAlias.GetActorRef()
    Actor kPlayer = Game.GetPlayer()
    If BogwifesKnife && kPlayer
        kPlayer.AddItem(BogwifesKnife, 1, True)
    EndIf
    ; Stage 100 FIRST: NHV_Pkg_Hrefna_CampWait (Q01 stage < 100) must be invalid before she is moved and
    ; re-evaluated, otherwise she walks straight back to her camp (ingame test 29.09.2026).
    SetStage(100)
    CompleteRecruitment(kHrefna, NHV_Status_Hrefna, HrefnaFamilySlotAlias, HrefnaAlias, KitchenMarker)
    bRecruitHomeChecked = True ; she was placed correctly just now
EndFunction

Function JudgeRelease()
    If GetStage() != 70
        Return
    EndIf
    If NHV_Status_Hrefna
        NHV_Status_Hrefna.SetValueInt(STATUS_RELEASED)
    EndIf
    fLetterDueGameTime = Utility.GetCurrentGameTime() + 7.0 ; 7 in-game days, concept section 7
    RegisterForSingleUpdateGameTime(168.0)
    SetStage(100)
EndFunction

Function JudgeSilence()
    If GetStage() != 70
        Return
    EndIf
    ; Set STATUS_KILLED immediately: the Brotherhood's judgement is final the moment it is spoken,
    ; regardless of whether the ensuing fight actually finishes her off in this session (she could
    ; flee, or the player could stop chasing). This guarantees the Global never sits at
    ; STATUS_UNKNOWN forever. RecruitDied() (triggered by her eventual OnDeath, whenever that
    ; happens) still fires the NHV_RecruitDied ModEvent - only the redundant SetValueInt is skipped
    ; there since the status already reads STATUS_KILLED.
    If NHV_Status_Hrefna
        NHV_Status_Hrefna.SetValueInt(STATUS_KILLED)
    EndIf
    If !HrefnaAlias
        NHV_Util.Log(NHV_Cfg_Debug, "JudgeSilence: HrefnaAlias property not set in the CK")
    Else
        Actor kHrefna = HrefnaAlias.GetActorRef()
        If kHrefna && !kHrefna.IsDead()
            ; NHV_Hrefna is Essential in the ESP (feedback 03.10.2026): the judgement "Silence" is the one intended death,
            ; so she becomes mortal right here, just before the fight (concept: "bei Freilassung oder ihrem Tod")
            kHrefna.GetActorBase().SetEssential(False)
            kHrefna.GetActorBase().SetProtected(False)
            kHrefna.StartCombat(Game.GetPlayer())
        EndIf
    EndIf
    SetStage(100)
EndFunction

; ---------------------------------------------------------------------------
; Release letter (game-time timer, fully independent of the OnUpdate cutscene watchdog above)
; ---------------------------------------------------------------------------
; CK NOTE (team lead, 28.09.2026): Stage 100 SHOULD be flagged "Complete Quest" - that only marks the
; quest completed in the journal, it keeps running and still receives OnUpdateGameTime/OnPlayerLoadGame.
; What must NOT happen before the release letter is delivered is Stop() / "Shut Down Quest": a stopped
; Q01 could never deliver the letter or reconcile the timer on load.
; Leave Stage 100 as the quest's final-but-not-completed stage instead (a common, intentional
; Bethesda pattern for exactly this reason); the Journal/Debrief plays identically either way. See
; docs/ck/M1.6-Q01-CK-Anleitung.md and docs/plan/Q01-The-Unanswered-Sacrament.md section 8b.

; Defense in depth for OnContractLoadGame() below and for the timer surviving an unexpected engine
; hiccup: always re-derives the wait from the stored absolute due time rather than trusting that a
; previously registered RegisterForSingleUpdateGameTime call is still pending.
Event OnUpdateGameTime()
    If fLetterDueGameTime <= 0.0
        Return ; stray callback, nothing pending
    EndIf
    Float fRemainingDays = fLetterDueGameTime - Utility.GetCurrentGameTime()
    If fRemainingDays <= 0.0
        fLetterDueGameTime = 0.0
        DeliverReleaseLetter()
    Else
        ; re-arm for exactly what is left; covers a load that jumped the clock forward or back
        RegisterForSingleUpdateGameTime(fRemainingDays * 24.0)
    EndIf
EndEvent

Function DeliverReleaseLetter()
    Actor kPlayer = Game.GetPlayer()
    If kPlayer && HrefnaReleaseLetter
        kPlayer.AddItem(HrefnaReleaseLetter, 1, True)
        NHV_Util.Log(NHV_Cfg_Debug, "DeliverReleaseLetter: letter delivered")
    EndIf
EndFunction

; Overrides NHV_ContractBaseScript.OnContractLoadGame(), called from
; NHV_ContractPlayerAliasScript.OnPlayerLoadGame(). Re-arms the release-letter timer on load: if
; fLetterDueGameTime is still pending but for any reason (engine hiccup, a future edit that stops
; the quest too early) no OnUpdateGameTime callback is currently scheduled, this makes sure one gets
; scheduled again instead of the letter silently never arriving. Safe to call even when a callback IS
; still pending - RegisterForSingleUpdateGameTime just replaces it with the same due time.
Function OnContractLoadGame()
    If GetStage() < 45
        SetQuintusAtFarm(False) ; quest (re)started before the Quintus decision: nobody waits on the farm
    EndIf
    If GetStage() != 50 || (VeyraTrialScene && !VeyraTrialScene.IsPlaying())
        ReleaseVeyraFromTrial() ; a hold from an interrupted trial must not outlive the trial scene
    EndIf
    If GetStage() >= 50
        MakeQuintusMortal() ; saves that reached stage 50 before this fix (ingame test 29.09.2026)
    EndIf
    If GetStage() >= 60 && GetStage() < 100
        StockQuintusBody() ; saves where Quintus died before his body carried the papers
    EndIf
    If GetStage() >= 60
        RestoreHrefnaAfterFight() ; no-op unless a fight state was left behind
    ElseIf GetStage() == 50
        Actor kQuintusDead = None
        If QuintusAlias
            kQuintusDead = QuintusAlias.GetActorRef()
        EndIf
        If kQuintusDead && kQuintusDead.IsDead()
            OnQuintusKilled(None) ; he died while the OnDeath event was missed (load, odd death): move on
        ElseIf bHrefnaWillKill && !bHrefnaAttacked
            RegisterForSingleUpdate(2.0) ; resume the kill watch after loading
        ElseIf bHrefnaAttacked && bHrefnaFought && kQuintusDead && kQuintusDead.Is3DLoaded() && HrefnaAlias
            ; save made mid-fight by a build before the assassination (30.09.2026): end that duel now
            Actor kHrefnaLoaded = HrefnaAlias.GetActorRef()
            If kHrefnaLoaded && !kHrefnaLoaded.IsDead()
                HrefnaAssassinatesQuintus(kHrefnaLoaded, kQuintusDead)
            EndIf
        EndIf
    EndIf
    If GetStage() >= 30
        bVeyraJoined = True ; saves past the farm: she is already part of the party
    EndIf
    If GetStage() >= 100 && !bTableOpened
        BeginDebriefWatch()
    EndIf
    If GetStage() >= 20 && GetStage() < 70
        BeginVeyraWatch() ; the watch is also needed in saves that reached stage 20 without the marker handover
    EndIf
    If GetStage() < 10
        bReedFightStarted = False ; quest (re)set: the reedbed starts from scratch
        bReedbedLootReleased = False
        bReedbedWatch = False
        bReedFightPending = False
        bDeathWatch = False
        bHakanDeathHandled = False
        bHrefnaDeathHandled = False
    Else
        BeginReedbedWatch() ; no-op once the sack is free (loot released or stage 20+)
        ArmDeathWatch()
    EndIf
    ReturnRecruitHome()
    bHomeWatch = False ; a load drops the timer: arm the homecoming watch again if it is due
    ArmHomeWatch()
    If GetStage() == 30 && !bCampAmbushDone
        bCampWatchStarted = False
        BeginCampWatch() ; the camp poll does not survive a load either
    EndIf
    If GetStage() == 25
        MakeScoutSafe() ; also clears a leftover ghost flag in saves
        EnsureScoutCursor()
    EndIf
    If bWatchpostWatch && GetStage() == 25
        RegisterForSingleUpdate(3.0)
    EndIf
    RearmWatches()
    If fLetterDueGameTime <= 0.0
        Return ; nothing pending
    EndIf
    Float fRemainingDays = fLetterDueGameTime - Utility.GetCurrentGameTime()
    If fRemainingDays <= 0.0
        fLetterDueGameTime = 0.0
        DeliverReleaseLetter()
    Else
        RegisterForSingleUpdateGameTime(fRemainingDays * 24.0)
    EndIf
EndFunction

; NHV_Quintus is Essential in the ESP so he cannot die before the trial. From stage 50 on he must be killable
; (by Hrefna or the player); ActorBase.SetEssential persists in the save. Idempotent.
Function MakeQuintusMortal()
    If !QuintusAlias
        Return
    EndIf
    Actor kQuintus = QuintusAlias.GetActorRef()
    If !kQuintus
        NHV_Util.Log(NHV_Cfg_Debug, "MakeQuintusMortal: QuintusAlias empty")
        Return
    EndIf
    ActorBase kBase = kQuintus.GetActorBase()
    If kBase.IsEssential()
        kBase.SetEssential(False)
        NHV_Util.Log(NHV_Cfg_Debug, "Quintus is no longer essential")
    EndIf
EndFunction

; Quintus' papers (field note + Oculatus fragment 1) on his body, so stage 60 "search his belongings" has
; something to find. Idempotent: only adds what the body and the player do not have yet.
Bool bBodyStocked = False
Bool bRecruitReturned = False       ; legacy one-shot (first repair, 29.09.2026), kept for saves
Bool bRecruitHomeChecked = False    ; second repair: she left again although the first check ran (CampWait still valid)

Function StockQuintusBody()
    If bBodyStocked || !QuintusAlias
        Return
    EndIf
    Actor kQuintus = QuintusAlias.GetActorRef()
    If !kQuintus
        Return
    EndIf
    Actor kPlayer = Game.GetPlayer()
    If QuintusFieldNote && kQuintus.GetItemCount(QuintusFieldNote) == 0 && kPlayer.GetItemCount(QuintusFieldNote) == 0
        kQuintus.AddItem(QuintusFieldNote, 1, True)
    EndIf
    If OculatusFragment1 && kQuintus.GetItemCount(OculatusFragment1) == 0 && kPlayer.GetItemCount(OculatusFragment1) == 0
        kQuintus.AddItem(OculatusFragment1, 1, True)
    EndIf
    bBodyStocked = True ; once: items the player drops or sells later are not restocked
EndFunction

; A recruited Hrefna walked back to her camp (CampWait had no stage condition before 29.09.2026): put her home.
Function ReturnRecruitHome()
    If bRecruitHomeChecked || GetStage() < 100 || !HrefnaFamilySlotAlias || !KitchenMarker || !NHV_Status_Hrefna
        Return
    EndIf
    If NHV_Status_Hrefna.GetValueInt() != STATUS_RECRUITED
        Return
    EndIf
    Actor kHrefna = HrefnaFamilySlotAlias.GetActorRef()
    If kHrefna && !kHrefna.IsDead() && kHrefna.GetParentCell() != KitchenMarker.GetParentCell()
        kHrefna.MoveTo(KitchenMarker)
        NHV_Util.Log(NHV_Cfg_Debug, "Hrefna returned to the Kitchen")
    EndIf
    If kHrefna && !kHrefna.IsDead()
        kHrefna.EvaluatePackage() ; also drops CampWait (stage 100 is done) for a save where she never left
    EndIf
    bRecruitHomeChecked = True ; one-time repair only; later family logic owns her position
EndFunction
